### ISSUE TITLE
Add the new feature to display servers motd

### ISSUE THREAD

**Issue by Catrainbow233** [hax0r31337/ProtoHax#16]
Protohax can't show server banners when staying at the main Interface.

**Comment by Aportye** [comment]
彩虹猫你在干什么😡

**Comment by hax0r31337** [comment]
closing due to this feature [is included on Android implementation](https://github.com/mccheatz/LibMITM/blob/raknet/raknet.go#L210), and there's no plan to introduce such feature to ProtoHax
