### ISSUE TITLE
Add some new modules

### ISSUE THREAD

**Issue by ztber666** [hax0r31337/ProtoHax#17]
Derp,TrueSight,NoFireCam,HitEffect.
And And raising kilaura's cps cap to 30 or higher.
I will be very happy if the suggestion is accepted.
That's all,thank you.

**Comment by LuciferNotPerfect** [comment]
auto crystal,reach,fix can't craft,fix hive map not load.

**Comment by hax0r31337** [comment]
`Derp` no plan   
`TrueSight` added into `AntiBlind`
`NoFireCam` added into `AntiBlind`
`HitEffect` added   
Raise KillAura CPS is useless
`AutoCrystal` is already exists as `CrystalAura`
Can't Craft unable to reproduce   
And can you tell me which mode exists maps in Hive server

**Comment by ztber666** [comment]
Deal with problems quickly, you are a good developer:)

**Comment by DucksMods** [comment]
@hax0r31337 when do you guys release?
