### ISSUE TITLE
you cant craft

### ISSUE THREAD

**Issue by MacNcheese0** [hax0r31337/ProtoHax#27]
if you wanted to craft a wooden sword you need crimson planks? I think the cause is different versions of Minecraft clashing with each other, as most servers use old versions of Minecraft, I tried using the 1.20.0 version
it still didn't work.

**Comment by hax0r31337** [comment]
no i can craft with ProtoHax on

![image](https://github.com/hax0r31337/ProtoHax/assets/65506006/0f92958e-842d-4cc9-91e1-9cd84d05455c)

**Comment by MacNcheese0** [comment]
> no i can craft with ProtoHax on
> 
> ![image](https://user-images.githubusercontent.com/65506006/250799506-0f92958e-842d-4cc9-91e1-9cd84d05455c.png)

must be a server issue I didn't try it on other servers mostly just lifeboat survival
