### ISSUE TITLE
stuck on "connecting external server"

### ISSUE THREAD

**Issue by notprofanta** [hax0r31337/ProtoHax#28]
im always stuck at "connecting to external server" how do i fix this?

**Comment by notprofanta** [comment]
logs:

VPN service destroyed
netstack started
client connected
logged in as notprofanta
SessionCreation /172.65.222.21:19132
server connected
selected codec (clientProtocol=589, protocol=589, mc=1.20.0)
selected compression algorithm: ZLIB
selected codec (clientProtocol=589, protocol=589, mc=1.20.0)
chain cache hit
login success
Encryption enabled for {}, /172.65.222.21:19132
awaiting mappings to load
Tried to close peer, but channel is open!: java.lang.Throwable
server disconnect: disconnect.timeout
client disconnect: disconnect.disconnected
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: go.Universe$proxyerror: read raknet 172.65.222.21:19132->10.13.37.1:44326: use of closed network connection

**Comment by hax0r31337** [comment]
fixed in commit 0caeb7762c56075de14e82639583b952868ff76e
