### ISSUE TITLE
[BUG]take a really long time and sometimes just doesn't connect to the server even after several attempts... probably something to do with the vpn

### ISSUE THREAD

**Issue by Kingcap001** [hax0r31337/ProtoHax#31]
**Describe the bug**

**To Reproduce**
1. Go to '.servers.'
2. Click on '.HIVE.'

**Expected behavior**
JOIN THE SERVER IN NORMAL TIME

**Screenshots**
I don't know how to send screenshot 

**Please complete the following information:**
 - Implementation: [e.g. ProtoHax-Android]
 - OS: [e.g. Android 13]
 - Version [e.g. 1.3.2]

**Additional context**

**Comment by RohanDaCoder** [comment]
its not about the vpn.. ProtoHax Works Through The Network Layer (Modifying Packets and sending them) 
And the vpn is what actually making ProtoHax work.

**Comment by hax0r31337** [comment]
duplicated with #28
