### ISSUE TITLE
Stuck at "Connecting to external server" 

### ISSUE THREAD

**Issue by Notnoahreally** [hax0r31337/ProtoHax#32]
**The Bug**

Minecraft is stuck at "Connecting to external server" when using the app on Android  

**Hypnosis**

-I think this ether caused by the server being used in the setting of the app because this only happens when I am not using "Use IPv6"
 but the problem is that the mod menu doesn't work when it's that setting.

**Conclusion**

-Minecraft gets stuck on "Connecting to external server" unless using IPv6
-When using IPv6 the mod menu and the app doesn't work

**Comment by hax0r31337** [comment]
duplicated with #28

**Comment by Notnoahreally** [comment]
When will the Android ver get patched? 
_You do not need to answer if you don't know ether_
