### ISSUE TITLE
[BUG] Crashing when trying to choose an application

### ISSUE THREAD

**Issue by VinkyV** [hax0r31337/ProtoHax#33]
OS: Android 12 / OneUI 4.1
Device: Samsung note 10+ N975U1
App version: 1.3.3
When I am trying to select an application, it's just closing.

Steps to reproduce:
Maybe try to open app on Samsung device and try to select an application.
Maybe KNOX doing something with it

**Comment by hax0r31337** [comment]
duplicated with https://github.com/hax0r31337/ProtoHax-Android/issues/37
