### ISSUE TITLE
[Features] Fix Killaura on Hive Server!!!

### ISSUE THREAD

**Issue by ghost** [hax0r31337/ProtoHax#5]
The Killaura just swinging but not dealing damage on Player
&
InventoryHelper,Disabler(Mineplex)(No Ping),BlockFly are not working properly.

**Comment by ghost** [comment]
Mineplex Disabler after on it has not do anything no respond on server, player freeze, no player packet.Fix it please😶

**Comment by hax0r31337** [comment]
> The Killaura just swinging but not dealing damage on Player & InventoryHelper,Disabler(Mineplex)(No Ping),BlockFly are not working properly.

I'm kinda busy IRL, but it will be fixed when i have some extra time

**Comment by ghost** [comment]
Any Update?I will be patient.

**Comment by AneryCoft** [comment]
> Mineplex Disabler after on it has not do anything no respond on server, player freeze, no player packet.Fix it please😶

Mineplex AntiCheat is update
